language: rust
rust: nightly

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=armv7r-none-eabi

    - env: TARGET=armv7r-none-eabi PAC=1

    - env: TARGET=aarch64-unknown-linux-musl

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
